In [1]:
a = range(0,5)

In [2]:
print (a)

range(0, 5)


In [3]:
import numpy as np

In [4]:
a = np.arange(0,10)

In [5]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a.size

10

In [7]:
b = np.linspace(0,10)

In [8]:
b

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [9]:
b.size

50

In [10]:
matriz = [[0,1,2],[3,4,5],[0,0,0]]

In [11]:
matriz

[[0, 1, 2], [3, 4, 5], [0, 0, 0]]

In [12]:
np.array(matriz)

array([[0, 1, 2],
       [3, 4, 5],
       [0, 0, 0]])

In [13]:
np.zeros([2,3,2,2])

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [14]:
arr = np.linspace(0, 100, 30)

In [15]:
arr

array([  0.        ,   3.44827586,   6.89655172,  10.34482759,
        13.79310345,  17.24137931,  20.68965517,  24.13793103,
        27.5862069 ,  31.03448276,  34.48275862,  37.93103448,
        41.37931034,  44.82758621,  48.27586207,  51.72413793,
        55.17241379,  58.62068966,  62.06896552,  65.51724138,
        68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
        82.75862069,  86.20689655,  89.65517241,  93.10344828,
        96.55172414, 100.        ])

In [16]:
arr.size

30

In [17]:
arr.shape

(30,)

In [18]:
arr = arr.reshape(3, 10)

In [19]:
arr

array([[  0.        ,   3.44827586,   6.89655172,  10.34482759,
         13.79310345,  17.24137931,  20.68965517,  24.13793103,
         27.5862069 ,  31.03448276],
       [ 34.48275862,  37.93103448,  41.37931034,  44.82758621,
         48.27586207,  51.72413793,  55.17241379,  58.62068966,
         62.06896552,  65.51724138],
       [ 68.96551724,  72.4137931 ,  75.86206897,  79.31034483,
         82.75862069,  86.20689655,  89.65517241,  93.10344828,
         96.55172414, 100.        ]])

In [20]:
arr[:, 2]

array([ 6.89655172, 41.37931034, 75.86206897])

In [21]:
arr[:][1]

array([34.48275862, 37.93103448, 41.37931034, 44.82758621, 48.27586207,
       51.72413793, 55.17241379, 58.62068966, 62.06896552, 65.51724138])

In [22]:
ran = np.arange(0,16)

In [23]:
ran

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [24]:
ran + ran

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [25]:
ran * 3

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45])

In [26]:
ran

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [27]:
ran * ran

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196, 225])

In [28]:
ran.size

16

In [29]:
ran2 = ran.reshape(4,4)

In [30]:
ran2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [31]:
 ran

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [32]:
ran.shape

(16,)

In [33]:
ran2.shape

(4, 4)

In [34]:
ran3 = np.arange(16,32)

In [35]:
ran3 = ran3.reshape(4,4)

In [36]:
ran3

array([[16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [37]:
ran2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [38]:
ran2 * ran3

array([[  0,  17,  36,  57],
       [ 80, 105, 132, 161],
       [192, 225, 260, 297],
       [336, 377, 420, 465]])

In [39]:
a = "oi"

In [40]:
print(a)

oi


In [41]:
import pandas as pd

In [45]:
labels = ['A', 'B', 'C','D']
dados = [1 , 2 , 3 , 4, ]

In [46]:
plan = pd.Series(dados, labels)

In [47]:
plan

A    1
B    2
C    3
D    4
dtype: int64

In [49]:
plan[2]

3

In [51]:
plan['D']

4

In [54]:
plan2 = pd.Series(['J', 'K', 'L', 'M'], [45, 44, 21, 33])

In [55]:
plan2

45    J
44    K
21    L
33    M
dtype: object

In [62]:
lista = np.random.randn(5,4)
lista

array([[-1.96693014e+00, -1.21564887e-03,  6.49550865e-01,
        -1.89763085e-01],
       [ 2.24436519e+00,  2.97308625e-01,  1.24421578e+00,
        -9.39442283e-01],
       [-1.23993993e+00, -4.92876492e-01, -1.00269819e-01,
        -3.05235797e+00],
       [ 2.05410535e-01,  1.18669358e+00,  9.21826299e-01,
         8.02741845e-01],
       [-7.43704849e-01,  4.93185820e-01, -1.14337862e+00,
        -1.06623919e-01]])

In [125]:
plan3 = pd.DataFrame(lista, ['A','B','C','D','E'], [1,2,3,4])

In [66]:
plan3

1         2         3         4
A -1.966930 -0.001216  0.649551 -0.189763
B  2.244365  0.297309  1.244216 -0.939442
C -1.239940 -0.492876 -0.100270 -3.052358
D  0.205411  1.186694  0.921826  0.802742
E -0.743705  0.493186 -1.143379 -0.106624

In [67]:
plan3[1]

A   -1.966930
B    2.244365
C   -1.239940
D    0.205411
E   -0.743705
Name: 1, dtype: float64

In [98]:
plan3[5] = [1,2,3,4,5]
plan3

1         2         3         4  5  5
A -1.966930 -0.001216  0.649551 -0.189763  1  1
B  2.244365  0.297309  1.244216 -0.939442  2  2
C -1.239940 -0.492876 -0.100270 -3.052358  3  3
D  0.205411  1.186694  0.921826  0.802742  4  4
E -0.743705  0.493186 -1.143379 -0.106624  5  5

In [101]:
plan3.drop(5,axis = 1, inplace = True)

In [102]:
plan3

1         2         3         4  5
A -1.966930 -0.001216  0.649551 -0.189763  1
B  2.244365  0.297309  1.244216 -0.939442  2
C -1.239940 -0.492876 -0.100270 -3.052358  3
D  0.205411  1.186694  0.921826  0.802742  4
E -0.743705  0.493186 -1.143379 -0.106624  5

In [103]:
plan3.loc['A',3]

0.6495508653666273

In [104]:
plan3.loc['A']

1   -1.966930
2   -0.001216
3    0.649551
4   -0.189763
5    1.000000
Name: A, dtype: float64

In [108]:
plan3.loc[['A','B','C','D','E'],[2]]

2
A -0.001216
B  0.297309
C -0.492876
D  1.186694
E  0.493186

In [118]:
plan3.iloc[:,1]

A   -0.001216
B    0.297309
C   -0.492876
D    1.186694
E    0.493186
Name: 2, dtype: float64

In [119]:
plan3

1         2         3         4  5
A -1.966930 -0.001216  0.649551 -0.189763  1
B  2.244365  0.297309  1.244216 -0.939442  2
C -1.239940 -0.492876 -0.100270 -3.052358  3
D  0.205411  1.186694  0.921826  0.802742  4
E -0.743705  0.493186 -1.143379 -0.106624  5

In [120]:
cond = plan3 > 0

In [121]:
plan3[cond]

1         2         3         4  5
A       NaN       NaN  0.649551       NaN  1
B  2.244365  0.297309  1.244216       NaN  2
C       NaN       NaN       NaN       NaN  3
D  0.205411  1.186694  0.921826  0.802742  4
E       NaN  0.493186       NaN       NaN  5

In [126]:
plan3

1         2         3         4
A -1.966930 -0.001216  0.649551 -0.189763
B  2.244365  0.297309  1.244216 -0.939442
C -1.239940 -0.492876 -0.100270 -3.052358
D  0.205411  1.186694  0.921826  0.802742
E -0.743705  0.493186 -1.143379 -0.106624

In [129]:
plan3[2] > 0

A    False
B     True
C    False
D     True
E     True
Name: 2, dtype: bool

In [130]:
plan3[plan3[2] > 0] 

1         2         3         4
B  2.244365  0.297309  1.244216 -0.939442
D  0.205411  1.186694  0.921826  0.802742
E -0.743705  0.493186 -1.143379 -0.106624

In [131]:
plan3

1         2         3         4
A -1.966930 -0.001216  0.649551 -0.189763
B  2.244365  0.297309  1.244216 -0.939442
C -1.239940 -0.492876 -0.100270 -3.052358
D  0.205411  1.186694  0.921826  0.802742
E -0.743705  0.493186 -1.143379 -0.106624

In [133]:
plan3.reset_index()

index         1         2         3         4
0     A -1.966930 -0.001216  0.649551 -0.189763
1     B  2.244365  0.297309  1.244216 -0.939442
2     C -1.239940 -0.492876 -0.100270 -3.052358
3     D  0.205411  1.186694  0.921826  0.802742
4     E -0.743705  0.493186 -1.143379 -0.106624

In [136]:
plan3.set_index(4,inplace =True)

In [137]:
plan3

1         2         3
4                                      
-0.189763 -1.966930 -0.001216  0.649551
-0.939442  2.244365  0.297309  1.244216
-3.052358 -1.239940 -0.492876 -0.100270
 0.802742  0.205411  1.186694  0.921826
-0.106624 -0.743705  0.493186 -1.143379